feat: release firmware v7.5.0
keepkey/keepkey-updater pull request #21
Opened 2022-11-17 18:20 UTC by pastaghost

* adds binary file containing keepkey firmware v7.5.0
* adds hash of firmware v7.5.0 binary to release manifest

2022-11-17 18:43 UTC, markrypt0 requested changes
Need to add latest firmware at top of releases.json 
https://github.com/keepkey/keepkey-updater/blob/d3c7cdbc9f2d9218b37077f881065908a0844f35/firmware/releases.json#L2

2022-11-17 19:18 UTC, markrypt0 approved these changes

2022-11-17 19:18 UTC, merged

2022-11-18 00:17 UTC, greatwolf commented
Is a changelog available for v7.5.0? https://github.com/keepkey/keepkey-firmware/releases is still on v7.4.0

2022-11-18 00:39 UTC, markrypt0 commented
Yes, sorry for the delay, it is now published.